# Generated by Django 5.0.6 on 2024-07-22 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Админы')),
            ],
            options={
                'verbose_name': 'Админ',
                'verbose_name_plural': 'Админы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Катергории',
            },
        ),
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Курьеры')),
                ('withOrder', models.BooleanField(verbose_name='С заказом')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='User iId')),
                ('withOrder', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'список заказов',
                'verbose_name_plural': 'списки заказов',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.CharField(max_length=200, verbose_name='Итого')),
                ('address', models.TextField(blank=True, default='Без адреса', verbose_name='Адрес клиента')),
                ('pay', models.CharField(max_length=250, verbose_name='Способ оплаты')),
                ('get_way', models.CharField(max_length=250, verbose_name='Способ получения')),
                ('number', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('CK', 'Cooking'), ('DL', 'Delivery'), ('RC', 'Received')], default='CK', max_length=250, verbose_name='Статус')),
                ('date', models.DateTimeField(verbose_name='Дата текущей позиции')),
                ('comment', models.TextField(blank=True, default='Без комментариев', verbose_name='Комментарий')),
                ('delivery_info', models.CharField(blank=True, default='Без информации', max_length=350, verbose_name='Информация о доставке')),
                ('promocode', models.CharField(blank=True, default='Без промокода', max_length=200, verbose_name='Промокод')),
                ('notify_cooks', models.BooleanField(default=False, verbose_name='Оповещение поваров')),
                ('notify_pickers', models.BooleanField(default=False, verbose_name='Оповещение сборщиков')),
                ('delivered', models.BooleanField(default=False, verbose_name='Оповещение о доставке 2')),
                ('notify_cooksDone', models.BooleanField(default=False, verbose_name='Оповещение поваров 2')),
                ('notify_pickersDone', models.BooleanField(default=False, verbose_name='Оповещение сборщиков 2')),
                ('deliveredDone', models.BooleanField(default=False, verbose_name='Оповещение о доставке')),
                ('cooked', models.BooleanField(default=False, verbose_name='Приготовлен')),
                ('ready', models.BooleanField(default=False, verbose_name='Собран')),
                ('deliveredSucces', models.BooleanField(default=False, verbose_name='Доставлен')),
                ('cooking_notifyed_user', models.BooleanField(default=False, verbose_name='Оповещение пользователя о готовке заказа')),
                ('picking_notifyed_user', models.BooleanField(default=False, verbose_name='Оповещение пользователя о сборке')),
                ('delivered_notifyed_user', models.BooleanField(default=False, verbose_name='Оповещение пользователя о доставке')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен')),
                ('phone_number', models.CharField(default='Неизвестно', max_length=200, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/media/menu_photos/', verbose_name='Фото')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('weight', models.CharField(max_length=250, verbose_name='Вес в граммах')),
                ('allergens', models.TextField(default='Без аллергенов', verbose_name='Аллергены')),
                ('energy_valuable', models.CharField(max_length=100, verbose_name='Энерг. ценность')),
                ('compounds', models.TextField(default='Ингединты', verbose_name='Список блюд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('isInDish', models.BooleanField(default=True)),
                ('dish', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('ingredients', models.TextField(verbose_name='Ингридиенты')),
                ('compounds', models.TextField(default='null', verbose_name='Долонительное')),
                ('quantity', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='main.orders')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='Сompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/media/compound_photos/', verbose_name='Фото')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('weight', models.CharField(max_length=250, verbose_name='Вес в граммах')),
                ('quantity', models.CharField(max_length=250, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('dish', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
            ],
            options={
                'verbose_name': 'Дополнительное',
                'verbose_name_plural': 'Дополнительные',
            },
        ),
    ]
