# Generated by Django 5.0.6 on 2024-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time_date',
            field=models.CharField(default='Самовывоз', max_length=300, verbose_name='Время доставки'),
        ),
    ]
